stages:
  - test27
  - test35
  - deploy

Unittest27:
  stage: test27
  tags:
    - docker
  image: mwirtz/python2.7-healpy
  script:
    - export PYTHONPATH=/builds/astro/astrotools
    - echo Start Unittests for python 2.7...
    - python test/test_auger.py -v
    - python test/test_coord.py -v
    - python test/test_cosmic_rays.py -v
    - python test/test_healpytools.py -v
    - python test/test_nucleitools.py -v
    - python test/test_obs.py -v
    - python test/test_simulations.py -v

Unittest35:
  stage: test35
  tags:
    - docker
  image: mwirtz/python3.5-healpy
  script:
    - export PYTHONPATH=/builds/astro/astrotools
    - echo Start Unittests for python 3.5...
    - python test/test_auger.py -v
    - python test/test_coord.py -v
    - python test/test_cosmic_rays.py -v
    - python test/test_healpytools.py -v
    - python test/test_nucleitools.py -v
    - python test/test_obs.py -v
    - python test/test_simulations.py -v

pages:
  stage: deploy
  tags:
    - docker
  image: alpine
  script:
    - apk --no-cache add py2-pip python-dev
    - pip install sphinx sphinx-rtd-theme sphinxcontrib-websupport
    - apk --no-cache add make
    - cd doc; make html
    - mv build/html/ public/
  artifacts:
    paths:
    - public
  only:
    - master

