stages:
  - test

dummy:
  stage: test
  tags:
    - docker
  image: martinurban/python2.7-healpy
  script:
    - echo $PYTHONPATH
    - export PYTHONPATH=$PYTHONPATH:/builds/astro/astrotools
    - echo $PYTHONPATH
    - echo Start Unittests
    - python test/test_coord.py -v
