stages:
  - test27
  - test35

Unittest27:
  stage: test27
  tags:
    - docker
  image: mwirtz/python2.7-healpy
  script:
    - export PYTHONPATH=/builds/astro/astrotools
    - echo Start Unittests...
    - python test/test_auger.py -v
    - python test/test_coord.py -v
    - python test/test_healpytools.py -v
    - python test/test_nucleitools.py -v
    - python test/test_obs.py -v
    - python test/test_simulations.py -v

Unittest35:
  stage: test35
  tags:
    - docker
  image: mwirtz/python3.5-healpy
  script:
    - export PYTHONPATH=/builds/astro/astrotools
    - echo Start Unittests...
    - python test/test_auger.py -v
    - python test/test_coord.py -v
    - python test/test_healpytools.py -v
    - python test/test_nucleitools.py -v
    - python test/test_obs.py -v
    - python test/test_simulations.py -v
