stages:
  - lint
  - unittest
  - deploy

Lint:
  stage: lint
  tags:
    - docker
  image: mwirtz/python2.7-healpy
  script:
    - pip install pylint flake8
    - export PYTHONPATH=/builds/astro/astrotools
    - pylint astrotools/atmosphere.py
    - pylint astrotools/auger.py
    - pylint astrotools/coord.py
    - pylint astrotools/cosmic_rays.py
    - pylint astrotools/gamale.py
    # ignore wildcard-import issues for healpytools, 
    # see also https://pylint.readthedocs.io/en/latest/technical_reference/features.html
    - pylint -d W0614,E0102,W0401 astrotools/healpytools.py  
    - pylint astrotools/nucleitools.py
    # - pylint astrotools/obs.py
    - pylint astrotools/simulations.py
    - pylint astrotools/skymap.py
    - pylint astrotools/stat.py


Unittest27:
  stage: unittest
  tags:
    - docker
  image: mwirtz/python2.7-healpy
  script:
    - export PYTHONPATH=/builds/astro/astrotools
    - echo Start Unittests for python 2.7...
    - python test/test_auger.py -v
    - python test/test_coord.py -v
    - python test/test_cosmic_rays.py -v
    - python test/test_gamale.py -v    
    - python test/test_healpytools.py -v
    - python test/test_nucleitools.py -v
    - python test/test_obs.py -v
    - python test/test_simulations.py -v

Unittest35:
  stage: unittest
  tags:
    - docker
  image: mwirtz/python3.5-healpy
  script:
    - export PYTHONPATH=/builds/astro/astrotools
    - echo Start Unittests for python 3.5...
    - python test/test_auger.py -v
    - python test/test_coord.py -v
    - python test/test_cosmic_rays.py -v
    - python test/test_gamale.py -v
    - python test/test_healpytools.py -v
    - python test/test_nucleitools.py -v
    - python test/test_obs.py -v
    - python test/test_simulations.py -v

pages:
  stage: deploy
  tags:
    - docker
  image: mwirtz/python2.7-healpy
  script:
    - pip install sphinx sphinx-rtd-theme sphinxcontrib-websupport
    - export PYTHONPATH=/builds/astro/astrotools
    - cd doc; make html
    - mv build/html/ ../public/
  artifacts:
    paths:
    - public
  only:
    - master
