stages:
  - test27

Unittest27:
  stage: test27
  tags:
    - docker
  image: martinurban/python2.7-healpy
  script:
    - export PYTHONPATH=/builds/astro/astrotools
    - echo Start Unittests...
    - python test/test_auger.py -v
    - python test/test_coord.py -v
    - python test/test_cosmic_rays.py -v
    - python test/test_gamale.py -v
    - python test/test_healpytools.py -v
    - python test/test_nucleitools.py -v
    - python test/test_obs.py -v
    - python test/test_simulations.py -v
